---
- name: Create kyverno namespace
  kubernetes.core.k8s:
    name: kyverno
    api_version: v1
    kind: Namespace
    state: present

- name: Add Kyverno Helm repo
  kubernetes.core.helm_repository:
    name: kyverno
    repo_url: "https://kyverno.github.io/kyverno/"

- name: Install Kyverno Policy Engine
  kubernetes.core.helm:
    name: kyverno
    chart_ref: kyverno/kyverno
    release_namespace: kyverno
    create_namespace: false
    state: present
