apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: falcosidekick-monitor
  namespace: flask-app
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: falcosidekick
  namespaceSelector:
    matchNames:
      - falco
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
