apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: default
  namespace: flask-app
spec:
  selector:
    matchLabels:
      app: devsecops-flask
  mtls:
    mode: STRICT
  portLevelMtls:
    5000:
      mode: PERMISSIVE
