apiVersion: v1
kind: Service
metadata:
  name: devsecops-flask
  namespace: flask-app
  labels:
    app: devsecops-flask
spec:
  ports:
    - port: 80
      targetPort: 5000
      name: http
  selector:
    app: devsecops-flask
